name: Building protobuf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: arthurzagidullin/pb-build:latest
    steps:
      - uses: actions/checkout@v2
        path: /app
      - run: |
          chmod +x /app/build-pb.sh
          /app/build-pb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: compiled.pb
          path: /artifacts

