name: Building protobuf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: arthurzagidullin/pb-build:latest
    steps:
      - uses: actions/checkout@v2
#      - run: echo $GITHUB_WORKSPACE
      - name: Build
        env:
          APP_DIR: /__w/building-pb/building-pb
        run: |
          chmod +x ${{env.APP_DIR}}/build-pb.sh
          ${{env.APP_DIR}}/build-pb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: compiled.pb
          path: /artifacts

