name: Building protobuf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: arthurzagidullin/pb-build:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          APP_DIR: $GITHUB_WORKSPACE
        run: |
          chmod +x $APP_DIR/build-pb.sh
          $APP_DIR/build-pb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: compiled.pb
          path: /artifacts

