name: Building protobuf
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: arthurzagidullin/pb-build:latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./build-pb.sh
      - run: mkdir /artifacts
      - run: ./build-pb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: golang.pb
          path: /artifacts

